### ISSUE TITLE
Python support broken with pyxmpp2?

### ISSUE THREAD

**Issue by Sepero** [lofyer/xmpp-ssh#1]
The Python client appears to depend on pyxmpp2.

When installing pyxmpp2

```
~# pip install pyxmpp2
Downloading/unpacking pyxmpp2
  Downloading pyxmpp2-2.0.0.tar.gz (652Kb): 652Kb downloaded
  Running setup.py egg_info for package pyxmpp2
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/failover/system/home/root/build/pyxmpp2/setup.py", line 6, in <module>
        from distribute_setup import use_setuptools
    ImportError: No module named distribute_setup
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/failover/system/home/root/build/pyxmpp2/setup.py", line 6, in <module>

    from distribute_setup import use_setuptools

ImportError: No module named distribute_setup

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /failover/system/home/root/build/pyxmpp2
Storing complete log in /root/.pip/pip.log
```

The Python modules `distribute` and `setuptools` are installed and appear to be up to date. I don't really know how to solve this.

**Comment by Sepero** [comment]
```
~# pip install setuptools --upgrade
Requirement already up-to-date: setuptools in /failover/system/usr/local/lib/python2.7/dist-packages
Cleaning up...
```

**Comment by lofyer** [comment]
# wget https://svn.apache.org/repos/asf/oodt/tools/oodtsite.publisher/trunk/distribute_setup.py

# python distribute_setup.py install

**Comment by Sepero** [comment]
Unfortunately, `pip install pyxmpp2` still gives the same error. :(

**Comment by lofyer** [comment]
I think you need python3 rather than python2
https://github.com/Jajcus/pyxmpp2
